# Generated by Django 6.0.4 on 2026-05-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTournamentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='ISO country code for national teams', max_length=10)),
                ('flag_url', models.URLField(blank=True)),
                ('is_national', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Language code, e.g. 'es', 'pt', 'fr'", max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Team Translation',
                'verbose_name_plural': 'Team Translations',
            },
        ),
        migrations.CreateModel(
            name='TemplateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('invitation_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False, help_text='When true, no new participants can join and the final ranking is locked.')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible_when_finished', models.BooleanField(default=True, help_text="If true, the tournament remains visible on the owner's dashboard after finishing.")),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('points', models.IntegerField()),
                ('exact_predictions', models.PositiveIntegerField(default=0, help_text='Predictions with 3 points (exact score)')),
                ('partial_predictions', models.PositiveIntegerField(default=0, help_text='Predictions with 1 point (correct outcome)')),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tournament', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('home_score_real', models.IntegerField(blank=True, null=True)),
                ('away_score_real', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('pool', 'Pool'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_matches', to='prode.predefinedtournamenttemplate')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_guess', models.IntegerField()),
                ('away_score_guess', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='prode.match')),
            ],
        ),
    ]
