# Generated by Django 6.0.4 on 2026-05-19 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_initial'),
        ('prode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='prode.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='prode.team'),
        ),
        migrations.AddField(
            model_name='teamtranslation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='prode.team'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_away_matches', to='prode.team'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_home_matches', to='prode.team'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='prode.predefinedtournamenttemplate'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_banner', to='media.uploadedimage'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediction',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='prode.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournaments',
            field=models.ManyToManyField(related_name='matches', to='prode.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentrankingsnapshot',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to='prode.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentrankingsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teamtranslation',
            unique_together={('team', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('user', 'tournament', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentrankingsnapshot',
            unique_together={('tournament', 'user')},
        ),
    ]
