# Generated by Django 6.0.4 on 2026-05-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0002_tournament_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournaments',
            field=models.ManyToManyField(related_name='matches', to='prode.tournament'),
        ),
    ]
