# Generated by Django 6.0.4 on 2026-05-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0003_match_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTournamentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='source',
            field=models.CharField(choices=[('pool', 'Pool'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.CreateModel(
            name='TemplateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='prode.predefinedtournamenttemplate')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
