# Generated by Django 6.0.4 on 2026-05-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0004_predefinedtournamenttemplate_match_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_matches', to='prode.predefinedtournamenttemplate'),
        ),
    ]
