# Generated by Django 6.0.4 on 2026-05-17 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('prode', '0006_match_teams_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_banner', to='media.uploadedimage'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='prode.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='prode.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, help_text='ISO country code for national teams', max_length=10),
        ),
        migrations.AlterField(
            model_name='templatematch',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_away_matches', to='prode.team'),
        ),
        migrations.AlterField(
            model_name='templatematch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_home_matches', to='prode.team'),
        ),
    ]
