# Generated by Django 6.0.4 on 2026-05-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0007_alter_team_options_tournament_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Language code, e.g. 'es', 'pt', 'fr'", max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='prode.team')),
            ],
            options={
                'verbose_name': 'Team Translation',
                'verbose_name_plural': 'Team Translations',
                'unique_together': {('team', 'language')},
            },
        ),
    ]
