# Generated by Django 6.0.4 on 2026-05-18 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0008_teamtranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='When true, no new participants can join and the final ranking is locked.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_visible_when_finished',
            field=models.BooleanField(default=True, help_text="If true, the tournament remains visible on the owner's dashboard after finishing."),
        ),
        migrations.CreateModel(
            name='TournamentRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('points', models.IntegerField()),
                ('exact_predictions', models.PositiveIntegerField(default=0, help_text='Predictions with 3 points (exact score)')),
                ('partial_predictions', models.PositiveIntegerField(default=0, help_text='Predictions with 1 point (correct outcome)')),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to='prode.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tournament', 'rank'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
